[package]
edition = "2021"
name = "number_to_words"

version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"

[dev-dependencies]
rstest = "0.15.0"
